// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meilisearch/meilisearch-go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockmeilisearchWebhookManager creates a new instance of MockmeilisearchWebhookManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockmeilisearchWebhookManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockmeilisearchWebhookManager {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockmeilisearchWebhookManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockmeilisearchWebhookManager is an autogenerated mock type for the WebhookManager type
type MockmeilisearchWebhookManager struct {
	mock.Mock
}

type MockmeilisearchWebhookManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockmeilisearchWebhookManager) EXPECT() *MockmeilisearchWebhookManager_Expecter {
	return &MockmeilisearchWebhookManager_Expecter{mock: &_m.Mock}
}

// AddWebhook provides a mock function for the type MockmeilisearchWebhookManager
func (_mock *MockmeilisearchWebhookManager) AddWebhook(ctx context.Context, params *meilisearch.AddWebhookRequest) (*meilisearch.Webhook, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for AddWebhook")
	}

	var r0 *meilisearch.Webhook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *meilisearch.AddWebhookRequest) (*meilisearch.Webhook, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *meilisearch.AddWebhookRequest) *meilisearch.Webhook); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.Webhook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *meilisearch.AddWebhookRequest) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchWebhookManager_AddWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWebhook'
type MockmeilisearchWebhookManager_AddWebhook_Call struct {
	*mock.Call
}

// AddWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - params *meilisearch.AddWebhookRequest
func (_e *MockmeilisearchWebhookManager_Expecter) AddWebhook(ctx any, params any) *MockmeilisearchWebhookManager_AddWebhook_Call {
	return &MockmeilisearchWebhookManager_AddWebhook_Call{Call: _e.mock.On("AddWebhook", ctx, params)}
}

func (_c *MockmeilisearchWebhookManager_AddWebhook_Call) Run(run func(ctx context.Context, params *meilisearch.AddWebhookRequest)) *MockmeilisearchWebhookManager_AddWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *meilisearch.AddWebhookRequest
		if args[1] != nil {
			arg1 = args[1].(*meilisearch.AddWebhookRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockmeilisearchWebhookManager_AddWebhook_Call) Return(webhook *meilisearch.Webhook, err error) *MockmeilisearchWebhookManager_AddWebhook_Call {
	_c.Call.Return(webhook, err)
	return _c
}

func (_c *MockmeilisearchWebhookManager_AddWebhook_Call) RunAndReturn(run func(ctx context.Context, params *meilisearch.AddWebhookRequest) (*meilisearch.Webhook, error)) *MockmeilisearchWebhookManager_AddWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWebhook provides a mock function for the type MockmeilisearchWebhookManager
func (_mock *MockmeilisearchWebhookManager) DeleteWebhook(ctx context.Context, uuid string) error {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWebhook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockmeilisearchWebhookManager_DeleteWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWebhook'
type MockmeilisearchWebhookManager_DeleteWebhook_Call struct {
	*mock.Call
}

// DeleteWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockmeilisearchWebhookManager_Expecter) DeleteWebhook(ctx any, uuid any) *MockmeilisearchWebhookManager_DeleteWebhook_Call {
	return &MockmeilisearchWebhookManager_DeleteWebhook_Call{Call: _e.mock.On("DeleteWebhook", ctx, uuid)}
}

func (_c *MockmeilisearchWebhookManager_DeleteWebhook_Call) Run(run func(ctx context.Context, uuid string)) *MockmeilisearchWebhookManager_DeleteWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockmeilisearchWebhookManager_DeleteWebhook_Call) Return(err error) *MockmeilisearchWebhookManager_DeleteWebhook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockmeilisearchWebhookManager_DeleteWebhook_Call) RunAndReturn(run func(ctx context.Context, uuid string) error) *MockmeilisearchWebhookManager_DeleteWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// GetWebhook provides a mock function for the type MockmeilisearchWebhookManager
func (_mock *MockmeilisearchWebhookManager) GetWebhook(ctx context.Context, uuid string) (*meilisearch.Webhook, error) {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetWebhook")
	}

	var r0 *meilisearch.Webhook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*meilisearch.Webhook, error)); ok {
		return returnFunc(ctx, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *meilisearch.Webhook); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.Webhook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchWebhookManager_GetWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWebhook'
type MockmeilisearchWebhookManager_GetWebhook_Call struct {
	*mock.Call
}

// GetWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockmeilisearchWebhookManager_Expecter) GetWebhook(ctx any, uuid any) *MockmeilisearchWebhookManager_GetWebhook_Call {
	return &MockmeilisearchWebhookManager_GetWebhook_Call{Call: _e.mock.On("GetWebhook", ctx, uuid)}
}

func (_c *MockmeilisearchWebhookManager_GetWebhook_Call) Run(run func(ctx context.Context, uuid string)) *MockmeilisearchWebhookManager_GetWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockmeilisearchWebhookManager_GetWebhook_Call) Return(webhook *meilisearch.Webhook, err error) *MockmeilisearchWebhookManager_GetWebhook_Call {
	_c.Call.Return(webhook, err)
	return _c
}

func (_c *MockmeilisearchWebhookManager_GetWebhook_Call) RunAndReturn(run func(ctx context.Context, uuid string) (*meilisearch.Webhook, error)) *MockmeilisearchWebhookManager_GetWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// ListWebhooks provides a mock function for the type MockmeilisearchWebhookManager
func (_mock *MockmeilisearchWebhookManager) ListWebhooks(ctx context.Context) (*meilisearch.WebhookResults, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListWebhooks")
	}

	var r0 *meilisearch.WebhookResults
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*meilisearch.WebhookResults, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *meilisearch.WebhookResults); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.WebhookResults)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchWebhookManager_ListWebhooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWebhooks'
type MockmeilisearchWebhookManager_ListWebhooks_Call struct {
	*mock.Call
}

// ListWebhooks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchWebhookManager_Expecter) ListWebhooks(ctx any) *MockmeilisearchWebhookManager_ListWebhooks_Call {
	return &MockmeilisearchWebhookManager_ListWebhooks_Call{Call: _e.mock.On("ListWebhooks", ctx)}
}

func (_c *MockmeilisearchWebhookManager_ListWebhooks_Call) Run(run func(ctx context.Context)) *MockmeilisearchWebhookManager_ListWebhooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchWebhookManager_ListWebhooks_Call) Return(webhookResults *meilisearch.WebhookResults, err error) *MockmeilisearchWebhookManager_ListWebhooks_Call {
	_c.Call.Return(webhookResults, err)
	return _c
}

func (_c *MockmeilisearchWebhookManager_ListWebhooks_Call) RunAndReturn(run func(ctx context.Context) (*meilisearch.WebhookResults, error)) *MockmeilisearchWebhookManager_ListWebhooks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWebhook provides a mock function for the type MockmeilisearchWebhookManager
func (_mock *MockmeilisearchWebhookManager) UpdateWebhook(ctx context.Context, uuid string, params *meilisearch.UpdateWebhookRequest) (*meilisearch.Webhook, error) {
	ret := _mock.Called(ctx, uuid, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWebhook")
	}

	var r0 *meilisearch.Webhook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *meilisearch.UpdateWebhookRequest) (*meilisearch.Webhook, error)); ok {
		return returnFunc(ctx, uuid, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *meilisearch.UpdateWebhookRequest) *meilisearch.Webhook); ok {
		r0 = returnFunc(ctx, uuid, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.Webhook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *meilisearch.UpdateWebhookRequest) error); ok {
		r1 = returnFunc(ctx, uuid, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchWebhookManager_UpdateWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWebhook'
type MockmeilisearchWebhookManager_UpdateWebhook_Call struct {
	*mock.Call
}

// UpdateWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - params *meilisearch.UpdateWebhookRequest
func (_e *MockmeilisearchWebhookManager_Expecter) UpdateWebhook(ctx any, uuid any, params any) *MockmeilisearchWebhookManager_UpdateWebhook_Call {
	return &MockmeilisearchWebhookManager_UpdateWebhook_Call{Call: _e.mock.On("UpdateWebhook", ctx, uuid, params)}
}

func (_c *MockmeilisearchWebhookManager_UpdateWebhook_Call) Run(run func(ctx context.Context, uuid string, params *meilisearch.UpdateWebhookRequest)) *MockmeilisearchWebhookManager_UpdateWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *meilisearch.UpdateWebhookRequest
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.UpdateWebhookRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockmeilisearchWebhookManager_UpdateWebhook_Call) Return(webhook *meilisearch.Webhook, err error) *MockmeilisearchWebhookManager_UpdateWebhook_Call {
	_c.Call.Return(webhook, err)
	return _c
}

func (_c *MockmeilisearchWebhookManager_UpdateWebhook_Call) RunAndReturn(run func(ctx context.Context, uuid string, params *meilisearch.UpdateWebhookRequest) (*meilisearch.Webhook, error)) *MockmeilisearchWebhookManager_UpdateWebhook_Call {
	_c.Call.Return(run)
	return _c
}
