// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/meilisearch/meilisearch-go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockmeilisearchDocumentManager creates a new instance of MockmeilisearchDocumentManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockmeilisearchDocumentManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockmeilisearchDocumentManager {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockmeilisearchDocumentManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockmeilisearchDocumentManager is an autogenerated mock type for the DocumentManager type
type MockmeilisearchDocumentManager struct {
	mock.Mock
}

type MockmeilisearchDocumentManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockmeilisearchDocumentManager) EXPECT() *MockmeilisearchDocumentManager_Expecter {
	return &MockmeilisearchDocumentManager_Expecter{mock: &_m.Mock}
}

// AddDocuments provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) AddDocuments(ctx context.Context, documentsPtr interface{}, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documentsPtr, opts)

	if len(ret) == 0 {
		panic("no return value specified for AddDocuments")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documentsPtr, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, *meilisearch.DocumentOptions) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documentsPtr, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, *meilisearch.DocumentOptions) error); ok {
		r1 = returnFunc(ctx, documentsPtr, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_AddDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDocuments'
type MockmeilisearchDocumentManager_AddDocuments_Call struct {
	*mock.Call
}

// AddDocuments is a helper method to define mock.On call
//   - ctx context.Context
//   - documentsPtr interface{}
//   - opts *meilisearch.DocumentOptions
func (_e *MockmeilisearchDocumentManager_Expecter) AddDocuments(ctx any, documentsPtr any, opts any) *MockmeilisearchDocumentManager_AddDocuments_Call {
	return &MockmeilisearchDocumentManager_AddDocuments_Call{Call: _e.mock.On("AddDocuments", ctx, documentsPtr, opts)}
}

func (_c *MockmeilisearchDocumentManager_AddDocuments_Call) Run(run func(ctx context.Context, documentsPtr interface{}, opts *meilisearch.DocumentOptions)) *MockmeilisearchDocumentManager_AddDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 *meilisearch.DocumentOptions
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.DocumentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocuments_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_AddDocuments_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocuments_Call) RunAndReturn(run func(ctx context.Context, documentsPtr interface{}, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_AddDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// AddDocumentsCsv provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) AddDocumentsCsv(ctx context.Context, documents []byte, options *meilisearch.CsvDocumentsQuery) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documents, options)

	if len(ret) == 0 {
		panic("no return value specified for AddDocumentsCsv")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, *meilisearch.CsvDocumentsQuery) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documents, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, *meilisearch.CsvDocumentsQuery) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documents, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, *meilisearch.CsvDocumentsQuery) error); ok {
		r1 = returnFunc(ctx, documents, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_AddDocumentsCsv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDocumentsCsv'
type MockmeilisearchDocumentManager_AddDocumentsCsv_Call struct {
	*mock.Call
}

// AddDocumentsCsv is a helper method to define mock.On call
//   - ctx context.Context
//   - documents []byte
//   - options *meilisearch.CsvDocumentsQuery
func (_e *MockmeilisearchDocumentManager_Expecter) AddDocumentsCsv(ctx any, documents any, options any) *MockmeilisearchDocumentManager_AddDocumentsCsv_Call {
	return &MockmeilisearchDocumentManager_AddDocumentsCsv_Call{Call: _e.mock.On("AddDocumentsCsv", ctx, documents, options)}
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsCsv_Call) Run(run func(ctx context.Context, documents []byte, options *meilisearch.CsvDocumentsQuery)) *MockmeilisearchDocumentManager_AddDocumentsCsv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 *meilisearch.CsvDocumentsQuery
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.CsvDocumentsQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsCsv_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_AddDocumentsCsv_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsCsv_Call) RunAndReturn(run func(ctx context.Context, documents []byte, options *meilisearch.CsvDocumentsQuery) (*meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_AddDocumentsCsv_Call {
	_c.Call.Return(run)
	return _c
}

// AddDocumentsCsvFromReader provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) AddDocumentsCsvFromReader(ctx context.Context, documents io.Reader, options *meilisearch.CsvDocumentsQuery) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documents, options)

	if len(ret) == 0 {
		panic("no return value specified for AddDocumentsCsvFromReader")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, *meilisearch.CsvDocumentsQuery) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documents, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, *meilisearch.CsvDocumentsQuery) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documents, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, *meilisearch.CsvDocumentsQuery) error); ok {
		r1 = returnFunc(ctx, documents, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_AddDocumentsCsvFromReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDocumentsCsvFromReader'
type MockmeilisearchDocumentManager_AddDocumentsCsvFromReader_Call struct {
	*mock.Call
}

// AddDocumentsCsvFromReader is a helper method to define mock.On call
//   - ctx context.Context
//   - documents io.Reader
//   - options *meilisearch.CsvDocumentsQuery
func (_e *MockmeilisearchDocumentManager_Expecter) AddDocumentsCsvFromReader(ctx any, documents any, options any) *MockmeilisearchDocumentManager_AddDocumentsCsvFromReader_Call {
	return &MockmeilisearchDocumentManager_AddDocumentsCsvFromReader_Call{Call: _e.mock.On("AddDocumentsCsvFromReader", ctx, documents, options)}
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsCsvFromReader_Call) Run(run func(ctx context.Context, documents io.Reader, options *meilisearch.CsvDocumentsQuery)) *MockmeilisearchDocumentManager_AddDocumentsCsvFromReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 *meilisearch.CsvDocumentsQuery
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.CsvDocumentsQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsCsvFromReader_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_AddDocumentsCsvFromReader_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsCsvFromReader_Call) RunAndReturn(run func(ctx context.Context, documents io.Reader, options *meilisearch.CsvDocumentsQuery) (*meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_AddDocumentsCsvFromReader_Call {
	_c.Call.Return(run)
	return _c
}

// AddDocumentsCsvFromReaderInBatches provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) AddDocumentsCsvFromReaderInBatches(ctx context.Context, documents io.Reader, batchSize int, options *meilisearch.CsvDocumentsQuery) ([]meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documents, batchSize, options)

	if len(ret) == 0 {
		panic("no return value specified for AddDocumentsCsvFromReaderInBatches")
	}

	var r0 []meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, int, *meilisearch.CsvDocumentsQuery) ([]meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documents, batchSize, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, int, *meilisearch.CsvDocumentsQuery) []meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documents, batchSize, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, int, *meilisearch.CsvDocumentsQuery) error); ok {
		r1 = returnFunc(ctx, documents, batchSize, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_AddDocumentsCsvFromReaderInBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDocumentsCsvFromReaderInBatches'
type MockmeilisearchDocumentManager_AddDocumentsCsvFromReaderInBatches_Call struct {
	*mock.Call
}

// AddDocumentsCsvFromReaderInBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - documents io.Reader
//   - batchSize int
//   - options *meilisearch.CsvDocumentsQuery
func (_e *MockmeilisearchDocumentManager_Expecter) AddDocumentsCsvFromReaderInBatches(ctx any, documents any, batchSize any, options any) *MockmeilisearchDocumentManager_AddDocumentsCsvFromReaderInBatches_Call {
	return &MockmeilisearchDocumentManager_AddDocumentsCsvFromReaderInBatches_Call{Call: _e.mock.On("AddDocumentsCsvFromReaderInBatches", ctx, documents, batchSize, options)}
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsCsvFromReaderInBatches_Call) Run(run func(ctx context.Context, documents io.Reader, batchSize int, options *meilisearch.CsvDocumentsQuery)) *MockmeilisearchDocumentManager_AddDocumentsCsvFromReaderInBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *meilisearch.CsvDocumentsQuery
		if args[3] != nil {
			arg3 = args[3].(*meilisearch.CsvDocumentsQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsCsvFromReaderInBatches_Call) Return(taskInfos []meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_AddDocumentsCsvFromReaderInBatches_Call {
	_c.Call.Return(taskInfos, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsCsvFromReaderInBatches_Call) RunAndReturn(run func(ctx context.Context, documents io.Reader, batchSize int, options *meilisearch.CsvDocumentsQuery) ([]meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_AddDocumentsCsvFromReaderInBatches_Call {
	_c.Call.Return(run)
	return _c
}

// AddDocumentsCsvInBatches provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) AddDocumentsCsvInBatches(ctx context.Context, documents []byte, batchSize int, options *meilisearch.CsvDocumentsQuery) ([]meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documents, batchSize, options)

	if len(ret) == 0 {
		panic("no return value specified for AddDocumentsCsvInBatches")
	}

	var r0 []meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int, *meilisearch.CsvDocumentsQuery) ([]meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documents, batchSize, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int, *meilisearch.CsvDocumentsQuery) []meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documents, batchSize, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, int, *meilisearch.CsvDocumentsQuery) error); ok {
		r1 = returnFunc(ctx, documents, batchSize, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_AddDocumentsCsvInBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDocumentsCsvInBatches'
type MockmeilisearchDocumentManager_AddDocumentsCsvInBatches_Call struct {
	*mock.Call
}

// AddDocumentsCsvInBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - documents []byte
//   - batchSize int
//   - options *meilisearch.CsvDocumentsQuery
func (_e *MockmeilisearchDocumentManager_Expecter) AddDocumentsCsvInBatches(ctx any, documents any, batchSize any, options any) *MockmeilisearchDocumentManager_AddDocumentsCsvInBatches_Call {
	return &MockmeilisearchDocumentManager_AddDocumentsCsvInBatches_Call{Call: _e.mock.On("AddDocumentsCsvInBatches", ctx, documents, batchSize, options)}
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsCsvInBatches_Call) Run(run func(ctx context.Context, documents []byte, batchSize int, options *meilisearch.CsvDocumentsQuery)) *MockmeilisearchDocumentManager_AddDocumentsCsvInBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *meilisearch.CsvDocumentsQuery
		if args[3] != nil {
			arg3 = args[3].(*meilisearch.CsvDocumentsQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsCsvInBatches_Call) Return(taskInfos []meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_AddDocumentsCsvInBatches_Call {
	_c.Call.Return(taskInfos, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsCsvInBatches_Call) RunAndReturn(run func(ctx context.Context, documents []byte, batchSize int, options *meilisearch.CsvDocumentsQuery) ([]meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_AddDocumentsCsvInBatches_Call {
	_c.Call.Return(run)
	return _c
}

// AddDocumentsInBatches provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) AddDocumentsInBatches(ctx context.Context, documentsPtr interface{}, batchSize int, opts *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documentsPtr, batchSize, opts)

	if len(ret) == 0 {
		panic("no return value specified for AddDocumentsInBatches")
	}

	var r0 []meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, int, *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documentsPtr, batchSize, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, int, *meilisearch.DocumentOptions) []meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documentsPtr, batchSize, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, int, *meilisearch.DocumentOptions) error); ok {
		r1 = returnFunc(ctx, documentsPtr, batchSize, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_AddDocumentsInBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDocumentsInBatches'
type MockmeilisearchDocumentManager_AddDocumentsInBatches_Call struct {
	*mock.Call
}

// AddDocumentsInBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - documentsPtr interface{}
//   - batchSize int
//   - opts *meilisearch.DocumentOptions
func (_e *MockmeilisearchDocumentManager_Expecter) AddDocumentsInBatches(ctx any, documentsPtr any, batchSize any, opts any) *MockmeilisearchDocumentManager_AddDocumentsInBatches_Call {
	return &MockmeilisearchDocumentManager_AddDocumentsInBatches_Call{Call: _e.mock.On("AddDocumentsInBatches", ctx, documentsPtr, batchSize, opts)}
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsInBatches_Call) Run(run func(ctx context.Context, documentsPtr interface{}, batchSize int, opts *meilisearch.DocumentOptions)) *MockmeilisearchDocumentManager_AddDocumentsInBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *meilisearch.DocumentOptions
		if args[3] != nil {
			arg3 = args[3].(*meilisearch.DocumentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsInBatches_Call) Return(taskInfos []meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_AddDocumentsInBatches_Call {
	_c.Call.Return(taskInfos, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsInBatches_Call) RunAndReturn(run func(ctx context.Context, documentsPtr interface{}, batchSize int, opts *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_AddDocumentsInBatches_Call {
	_c.Call.Return(run)
	return _c
}

// AddDocumentsNdjson provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) AddDocumentsNdjson(ctx context.Context, documents []byte, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documents, opts)

	if len(ret) == 0 {
		panic("no return value specified for AddDocumentsNdjson")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documents, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, *meilisearch.DocumentOptions) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documents, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, *meilisearch.DocumentOptions) error); ok {
		r1 = returnFunc(ctx, documents, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_AddDocumentsNdjson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDocumentsNdjson'
type MockmeilisearchDocumentManager_AddDocumentsNdjson_Call struct {
	*mock.Call
}

// AddDocumentsNdjson is a helper method to define mock.On call
//   - ctx context.Context
//   - documents []byte
//   - opts *meilisearch.DocumentOptions
func (_e *MockmeilisearchDocumentManager_Expecter) AddDocumentsNdjson(ctx any, documents any, opts any) *MockmeilisearchDocumentManager_AddDocumentsNdjson_Call {
	return &MockmeilisearchDocumentManager_AddDocumentsNdjson_Call{Call: _e.mock.On("AddDocumentsNdjson", ctx, documents, opts)}
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsNdjson_Call) Run(run func(ctx context.Context, documents []byte, opts *meilisearch.DocumentOptions)) *MockmeilisearchDocumentManager_AddDocumentsNdjson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 *meilisearch.DocumentOptions
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.DocumentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsNdjson_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_AddDocumentsNdjson_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsNdjson_Call) RunAndReturn(run func(ctx context.Context, documents []byte, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_AddDocumentsNdjson_Call {
	_c.Call.Return(run)
	return _c
}

// AddDocumentsNdjsonFromReader provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) AddDocumentsNdjsonFromReader(ctx context.Context, documents io.Reader, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documents, opts)

	if len(ret) == 0 {
		panic("no return value specified for AddDocumentsNdjsonFromReader")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documents, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, *meilisearch.DocumentOptions) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documents, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, *meilisearch.DocumentOptions) error); ok {
		r1 = returnFunc(ctx, documents, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDocumentsNdjsonFromReader'
type MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReader_Call struct {
	*mock.Call
}

// AddDocumentsNdjsonFromReader is a helper method to define mock.On call
//   - ctx context.Context
//   - documents io.Reader
//   - opts *meilisearch.DocumentOptions
func (_e *MockmeilisearchDocumentManager_Expecter) AddDocumentsNdjsonFromReader(ctx any, documents any, opts any) *MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReader_Call {
	return &MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReader_Call{Call: _e.mock.On("AddDocumentsNdjsonFromReader", ctx, documents, opts)}
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReader_Call) Run(run func(ctx context.Context, documents io.Reader, opts *meilisearch.DocumentOptions)) *MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 *meilisearch.DocumentOptions
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.DocumentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReader_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReader_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReader_Call) RunAndReturn(run func(ctx context.Context, documents io.Reader, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReader_Call {
	_c.Call.Return(run)
	return _c
}

// AddDocumentsNdjsonFromReaderInBatches provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) AddDocumentsNdjsonFromReaderInBatches(ctx context.Context, documents io.Reader, batchSize int, opts *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documents, batchSize, opts)

	if len(ret) == 0 {
		panic("no return value specified for AddDocumentsNdjsonFromReaderInBatches")
	}

	var r0 []meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, int, *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documents, batchSize, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, int, *meilisearch.DocumentOptions) []meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documents, batchSize, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, int, *meilisearch.DocumentOptions) error); ok {
		r1 = returnFunc(ctx, documents, batchSize, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReaderInBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDocumentsNdjsonFromReaderInBatches'
type MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReaderInBatches_Call struct {
	*mock.Call
}

// AddDocumentsNdjsonFromReaderInBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - documents io.Reader
//   - batchSize int
//   - opts *meilisearch.DocumentOptions
func (_e *MockmeilisearchDocumentManager_Expecter) AddDocumentsNdjsonFromReaderInBatches(ctx any, documents any, batchSize any, opts any) *MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReaderInBatches_Call {
	return &MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReaderInBatches_Call{Call: _e.mock.On("AddDocumentsNdjsonFromReaderInBatches", ctx, documents, batchSize, opts)}
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReaderInBatches_Call) Run(run func(ctx context.Context, documents io.Reader, batchSize int, opts *meilisearch.DocumentOptions)) *MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReaderInBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *meilisearch.DocumentOptions
		if args[3] != nil {
			arg3 = args[3].(*meilisearch.DocumentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReaderInBatches_Call) Return(taskInfos []meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReaderInBatches_Call {
	_c.Call.Return(taskInfos, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReaderInBatches_Call) RunAndReturn(run func(ctx context.Context, documents io.Reader, batchSize int, opts *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_AddDocumentsNdjsonFromReaderInBatches_Call {
	_c.Call.Return(run)
	return _c
}

// AddDocumentsNdjsonInBatches provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) AddDocumentsNdjsonInBatches(ctx context.Context, documents []byte, batchSize int, opts *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documents, batchSize, opts)

	if len(ret) == 0 {
		panic("no return value specified for AddDocumentsNdjsonInBatches")
	}

	var r0 []meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int, *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documents, batchSize, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int, *meilisearch.DocumentOptions) []meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documents, batchSize, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, int, *meilisearch.DocumentOptions) error); ok {
		r1 = returnFunc(ctx, documents, batchSize, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_AddDocumentsNdjsonInBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDocumentsNdjsonInBatches'
type MockmeilisearchDocumentManager_AddDocumentsNdjsonInBatches_Call struct {
	*mock.Call
}

// AddDocumentsNdjsonInBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - documents []byte
//   - batchSize int
//   - opts *meilisearch.DocumentOptions
func (_e *MockmeilisearchDocumentManager_Expecter) AddDocumentsNdjsonInBatches(ctx any, documents any, batchSize any, opts any) *MockmeilisearchDocumentManager_AddDocumentsNdjsonInBatches_Call {
	return &MockmeilisearchDocumentManager_AddDocumentsNdjsonInBatches_Call{Call: _e.mock.On("AddDocumentsNdjsonInBatches", ctx, documents, batchSize, opts)}
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsNdjsonInBatches_Call) Run(run func(ctx context.Context, documents []byte, batchSize int, opts *meilisearch.DocumentOptions)) *MockmeilisearchDocumentManager_AddDocumentsNdjsonInBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *meilisearch.DocumentOptions
		if args[3] != nil {
			arg3 = args[3].(*meilisearch.DocumentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsNdjsonInBatches_Call) Return(taskInfos []meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_AddDocumentsNdjsonInBatches_Call {
	_c.Call.Return(taskInfos, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_AddDocumentsNdjsonInBatches_Call) RunAndReturn(run func(ctx context.Context, documents []byte, batchSize int, opts *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_AddDocumentsNdjsonInBatches_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllDocuments provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) DeleteAllDocuments(ctx context.Context, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllDocuments")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *meilisearch.DocumentOptions) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *meilisearch.DocumentOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_DeleteAllDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllDocuments'
type MockmeilisearchDocumentManager_DeleteAllDocuments_Call struct {
	*mock.Call
}

// DeleteAllDocuments is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *meilisearch.DocumentOptions
func (_e *MockmeilisearchDocumentManager_Expecter) DeleteAllDocuments(ctx any, opts any) *MockmeilisearchDocumentManager_DeleteAllDocuments_Call {
	return &MockmeilisearchDocumentManager_DeleteAllDocuments_Call{Call: _e.mock.On("DeleteAllDocuments", ctx, opts)}
}

func (_c *MockmeilisearchDocumentManager_DeleteAllDocuments_Call) Run(run func(ctx context.Context, opts *meilisearch.DocumentOptions)) *MockmeilisearchDocumentManager_DeleteAllDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *meilisearch.DocumentOptions
		if args[1] != nil {
			arg1 = args[1].(*meilisearch.DocumentOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_DeleteAllDocuments_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_DeleteAllDocuments_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_DeleteAllDocuments_Call) RunAndReturn(run func(ctx context.Context, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_DeleteAllDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDocument provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) DeleteDocument(ctx context.Context, identifier string, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, identifier, opts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocument")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, identifier, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *meilisearch.DocumentOptions) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, identifier, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *meilisearch.DocumentOptions) error); ok {
		r1 = returnFunc(ctx, identifier, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_DeleteDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDocument'
type MockmeilisearchDocumentManager_DeleteDocument_Call struct {
	*mock.Call
}

// DeleteDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
//   - opts *meilisearch.DocumentOptions
func (_e *MockmeilisearchDocumentManager_Expecter) DeleteDocument(ctx any, identifier any, opts any) *MockmeilisearchDocumentManager_DeleteDocument_Call {
	return &MockmeilisearchDocumentManager_DeleteDocument_Call{Call: _e.mock.On("DeleteDocument", ctx, identifier, opts)}
}

func (_c *MockmeilisearchDocumentManager_DeleteDocument_Call) Run(run func(ctx context.Context, identifier string, opts *meilisearch.DocumentOptions)) *MockmeilisearchDocumentManager_DeleteDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *meilisearch.DocumentOptions
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.DocumentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_DeleteDocument_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_DeleteDocument_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_DeleteDocument_Call) RunAndReturn(run func(ctx context.Context, identifier string, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_DeleteDocument_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDocuments provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) DeleteDocuments(ctx context.Context, identifiers []string, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, identifiers, opts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocuments")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, identifiers, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, *meilisearch.DocumentOptions) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, identifiers, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, *meilisearch.DocumentOptions) error); ok {
		r1 = returnFunc(ctx, identifiers, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_DeleteDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDocuments'
type MockmeilisearchDocumentManager_DeleteDocuments_Call struct {
	*mock.Call
}

// DeleteDocuments is a helper method to define mock.On call
//   - ctx context.Context
//   - identifiers []string
//   - opts *meilisearch.DocumentOptions
func (_e *MockmeilisearchDocumentManager_Expecter) DeleteDocuments(ctx any, identifiers any, opts any) *MockmeilisearchDocumentManager_DeleteDocuments_Call {
	return &MockmeilisearchDocumentManager_DeleteDocuments_Call{Call: _e.mock.On("DeleteDocuments", ctx, identifiers, opts)}
}

func (_c *MockmeilisearchDocumentManager_DeleteDocuments_Call) Run(run func(ctx context.Context, identifiers []string, opts *meilisearch.DocumentOptions)) *MockmeilisearchDocumentManager_DeleteDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 *meilisearch.DocumentOptions
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.DocumentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_DeleteDocuments_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_DeleteDocuments_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_DeleteDocuments_Call) RunAndReturn(run func(ctx context.Context, identifiers []string, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_DeleteDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDocumentsByFilter provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) DeleteDocumentsByFilter(ctx context.Context, filter interface{}, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, filter, opts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocumentsByFilter")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, filter, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, *meilisearch.DocumentOptions) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, filter, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, *meilisearch.DocumentOptions) error); ok {
		r1 = returnFunc(ctx, filter, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_DeleteDocumentsByFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDocumentsByFilter'
type MockmeilisearchDocumentManager_DeleteDocumentsByFilter_Call struct {
	*mock.Call
}

// DeleteDocumentsByFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts *meilisearch.DocumentOptions
func (_e *MockmeilisearchDocumentManager_Expecter) DeleteDocumentsByFilter(ctx any, filter any, opts any) *MockmeilisearchDocumentManager_DeleteDocumentsByFilter_Call {
	return &MockmeilisearchDocumentManager_DeleteDocumentsByFilter_Call{Call: _e.mock.On("DeleteDocumentsByFilter", ctx, filter, opts)}
}

func (_c *MockmeilisearchDocumentManager_DeleteDocumentsByFilter_Call) Run(run func(ctx context.Context, filter interface{}, opts *meilisearch.DocumentOptions)) *MockmeilisearchDocumentManager_DeleteDocumentsByFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 *meilisearch.DocumentOptions
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.DocumentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_DeleteDocumentsByFilter_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_DeleteDocumentsByFilter_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_DeleteDocumentsByFilter_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_DeleteDocumentsByFilter_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocument provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) GetDocument(ctx context.Context, identifier string, request *meilisearch.DocumentQuery, documentPtr interface{}) error {
	ret := _mock.Called(ctx, identifier, request, documentPtr)

	if len(ret) == 0 {
		panic("no return value specified for GetDocument")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *meilisearch.DocumentQuery, interface{}) error); ok {
		r0 = returnFunc(ctx, identifier, request, documentPtr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockmeilisearchDocumentManager_GetDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocument'
type MockmeilisearchDocumentManager_GetDocument_Call struct {
	*mock.Call
}

// GetDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
//   - request *meilisearch.DocumentQuery
//   - documentPtr interface{}
func (_e *MockmeilisearchDocumentManager_Expecter) GetDocument(ctx any, identifier any, request any, documentPtr any) *MockmeilisearchDocumentManager_GetDocument_Call {
	return &MockmeilisearchDocumentManager_GetDocument_Call{Call: _e.mock.On("GetDocument", ctx, identifier, request, documentPtr)}
}

func (_c *MockmeilisearchDocumentManager_GetDocument_Call) Run(run func(ctx context.Context, identifier string, request *meilisearch.DocumentQuery, documentPtr interface{})) *MockmeilisearchDocumentManager_GetDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *meilisearch.DocumentQuery
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.DocumentQuery)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_GetDocument_Call) Return(err error) *MockmeilisearchDocumentManager_GetDocument_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_GetDocument_Call) RunAndReturn(run func(ctx context.Context, identifier string, request *meilisearch.DocumentQuery, documentPtr interface{}) error) *MockmeilisearchDocumentManager_GetDocument_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocuments provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) GetDocuments(ctx context.Context, param *meilisearch.DocumentsQuery, resp *meilisearch.DocumentsResult) error {
	ret := _mock.Called(ctx, param, resp)

	if len(ret) == 0 {
		panic("no return value specified for GetDocuments")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *meilisearch.DocumentsQuery, *meilisearch.DocumentsResult) error); ok {
		r0 = returnFunc(ctx, param, resp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockmeilisearchDocumentManager_GetDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocuments'
type MockmeilisearchDocumentManager_GetDocuments_Call struct {
	*mock.Call
}

// GetDocuments is a helper method to define mock.On call
//   - ctx context.Context
//   - param *meilisearch.DocumentsQuery
//   - resp *meilisearch.DocumentsResult
func (_e *MockmeilisearchDocumentManager_Expecter) GetDocuments(ctx any, param any, resp any) *MockmeilisearchDocumentManager_GetDocuments_Call {
	return &MockmeilisearchDocumentManager_GetDocuments_Call{Call: _e.mock.On("GetDocuments", ctx, param, resp)}
}

func (_c *MockmeilisearchDocumentManager_GetDocuments_Call) Run(run func(ctx context.Context, param *meilisearch.DocumentsQuery, resp *meilisearch.DocumentsResult)) *MockmeilisearchDocumentManager_GetDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *meilisearch.DocumentsQuery
		if args[1] != nil {
			arg1 = args[1].(*meilisearch.DocumentsQuery)
		}
		var arg2 *meilisearch.DocumentsResult
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.DocumentsResult)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_GetDocuments_Call) Return(err error) *MockmeilisearchDocumentManager_GetDocuments_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_GetDocuments_Call) RunAndReturn(run func(ctx context.Context, param *meilisearch.DocumentsQuery, resp *meilisearch.DocumentsResult) error) *MockmeilisearchDocumentManager_GetDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocuments provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) UpdateDocuments(ctx context.Context, documentsPtr interface{}, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documentsPtr, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocuments")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documentsPtr, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, *meilisearch.DocumentOptions) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documentsPtr, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, *meilisearch.DocumentOptions) error); ok {
		r1 = returnFunc(ctx, documentsPtr, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_UpdateDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocuments'
type MockmeilisearchDocumentManager_UpdateDocuments_Call struct {
	*mock.Call
}

// UpdateDocuments is a helper method to define mock.On call
//   - ctx context.Context
//   - documentsPtr interface{}
//   - opts *meilisearch.DocumentOptions
func (_e *MockmeilisearchDocumentManager_Expecter) UpdateDocuments(ctx any, documentsPtr any, opts any) *MockmeilisearchDocumentManager_UpdateDocuments_Call {
	return &MockmeilisearchDocumentManager_UpdateDocuments_Call{Call: _e.mock.On("UpdateDocuments", ctx, documentsPtr, opts)}
}

func (_c *MockmeilisearchDocumentManager_UpdateDocuments_Call) Run(run func(ctx context.Context, documentsPtr interface{}, opts *meilisearch.DocumentOptions)) *MockmeilisearchDocumentManager_UpdateDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 *meilisearch.DocumentOptions
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.DocumentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_UpdateDocuments_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_UpdateDocuments_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_UpdateDocuments_Call) RunAndReturn(run func(ctx context.Context, documentsPtr interface{}, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_UpdateDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocumentsByFunction provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) UpdateDocumentsByFunction(ctx context.Context, req *meilisearch.UpdateDocumentByFunctionRequest) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocumentsByFunction")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *meilisearch.UpdateDocumentByFunctionRequest) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *meilisearch.UpdateDocumentByFunctionRequest) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *meilisearch.UpdateDocumentByFunctionRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_UpdateDocumentsByFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocumentsByFunction'
type MockmeilisearchDocumentManager_UpdateDocumentsByFunction_Call struct {
	*mock.Call
}

// UpdateDocumentsByFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - req *meilisearch.UpdateDocumentByFunctionRequest
func (_e *MockmeilisearchDocumentManager_Expecter) UpdateDocumentsByFunction(ctx any, req any) *MockmeilisearchDocumentManager_UpdateDocumentsByFunction_Call {
	return &MockmeilisearchDocumentManager_UpdateDocumentsByFunction_Call{Call: _e.mock.On("UpdateDocumentsByFunction", ctx, req)}
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsByFunction_Call) Run(run func(ctx context.Context, req *meilisearch.UpdateDocumentByFunctionRequest)) *MockmeilisearchDocumentManager_UpdateDocumentsByFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *meilisearch.UpdateDocumentByFunctionRequest
		if args[1] != nil {
			arg1 = args[1].(*meilisearch.UpdateDocumentByFunctionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsByFunction_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_UpdateDocumentsByFunction_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsByFunction_Call) RunAndReturn(run func(ctx context.Context, req *meilisearch.UpdateDocumentByFunctionRequest) (*meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_UpdateDocumentsByFunction_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocumentsCsv provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) UpdateDocumentsCsv(ctx context.Context, documents []byte, options *meilisearch.CsvDocumentsQuery) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documents, options)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocumentsCsv")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, *meilisearch.CsvDocumentsQuery) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documents, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, *meilisearch.CsvDocumentsQuery) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documents, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, *meilisearch.CsvDocumentsQuery) error); ok {
		r1 = returnFunc(ctx, documents, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_UpdateDocumentsCsv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocumentsCsv'
type MockmeilisearchDocumentManager_UpdateDocumentsCsv_Call struct {
	*mock.Call
}

// UpdateDocumentsCsv is a helper method to define mock.On call
//   - ctx context.Context
//   - documents []byte
//   - options *meilisearch.CsvDocumentsQuery
func (_e *MockmeilisearchDocumentManager_Expecter) UpdateDocumentsCsv(ctx any, documents any, options any) *MockmeilisearchDocumentManager_UpdateDocumentsCsv_Call {
	return &MockmeilisearchDocumentManager_UpdateDocumentsCsv_Call{Call: _e.mock.On("UpdateDocumentsCsv", ctx, documents, options)}
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsCsv_Call) Run(run func(ctx context.Context, documents []byte, options *meilisearch.CsvDocumentsQuery)) *MockmeilisearchDocumentManager_UpdateDocumentsCsv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 *meilisearch.CsvDocumentsQuery
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.CsvDocumentsQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsCsv_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_UpdateDocumentsCsv_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsCsv_Call) RunAndReturn(run func(ctx context.Context, documents []byte, options *meilisearch.CsvDocumentsQuery) (*meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_UpdateDocumentsCsv_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocumentsCsvInBatches provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) UpdateDocumentsCsvInBatches(ctx context.Context, documents []byte, batchsize int, options *meilisearch.CsvDocumentsQuery) ([]meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documents, batchsize, options)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocumentsCsvInBatches")
	}

	var r0 []meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int, *meilisearch.CsvDocumentsQuery) ([]meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documents, batchsize, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int, *meilisearch.CsvDocumentsQuery) []meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documents, batchsize, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, int, *meilisearch.CsvDocumentsQuery) error); ok {
		r1 = returnFunc(ctx, documents, batchsize, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_UpdateDocumentsCsvInBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocumentsCsvInBatches'
type MockmeilisearchDocumentManager_UpdateDocumentsCsvInBatches_Call struct {
	*mock.Call
}

// UpdateDocumentsCsvInBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - documents []byte
//   - batchsize int
//   - options *meilisearch.CsvDocumentsQuery
func (_e *MockmeilisearchDocumentManager_Expecter) UpdateDocumentsCsvInBatches(ctx any, documents any, batchsize any, options any) *MockmeilisearchDocumentManager_UpdateDocumentsCsvInBatches_Call {
	return &MockmeilisearchDocumentManager_UpdateDocumentsCsvInBatches_Call{Call: _e.mock.On("UpdateDocumentsCsvInBatches", ctx, documents, batchsize, options)}
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsCsvInBatches_Call) Run(run func(ctx context.Context, documents []byte, batchsize int, options *meilisearch.CsvDocumentsQuery)) *MockmeilisearchDocumentManager_UpdateDocumentsCsvInBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *meilisearch.CsvDocumentsQuery
		if args[3] != nil {
			arg3 = args[3].(*meilisearch.CsvDocumentsQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsCsvInBatches_Call) Return(taskInfos []meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_UpdateDocumentsCsvInBatches_Call {
	_c.Call.Return(taskInfos, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsCsvInBatches_Call) RunAndReturn(run func(ctx context.Context, documents []byte, batchsize int, options *meilisearch.CsvDocumentsQuery) ([]meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_UpdateDocumentsCsvInBatches_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocumentsInBatches provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) UpdateDocumentsInBatches(ctx context.Context, documentsPtr interface{}, batchSize int, opts *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documentsPtr, batchSize, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocumentsInBatches")
	}

	var r0 []meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, int, *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documentsPtr, batchSize, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, int, *meilisearch.DocumentOptions) []meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documentsPtr, batchSize, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, int, *meilisearch.DocumentOptions) error); ok {
		r1 = returnFunc(ctx, documentsPtr, batchSize, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_UpdateDocumentsInBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocumentsInBatches'
type MockmeilisearchDocumentManager_UpdateDocumentsInBatches_Call struct {
	*mock.Call
}

// UpdateDocumentsInBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - documentsPtr interface{}
//   - batchSize int
//   - opts *meilisearch.DocumentOptions
func (_e *MockmeilisearchDocumentManager_Expecter) UpdateDocumentsInBatches(ctx any, documentsPtr any, batchSize any, opts any) *MockmeilisearchDocumentManager_UpdateDocumentsInBatches_Call {
	return &MockmeilisearchDocumentManager_UpdateDocumentsInBatches_Call{Call: _e.mock.On("UpdateDocumentsInBatches", ctx, documentsPtr, batchSize, opts)}
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsInBatches_Call) Run(run func(ctx context.Context, documentsPtr interface{}, batchSize int, opts *meilisearch.DocumentOptions)) *MockmeilisearchDocumentManager_UpdateDocumentsInBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *meilisearch.DocumentOptions
		if args[3] != nil {
			arg3 = args[3].(*meilisearch.DocumentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsInBatches_Call) Return(taskInfos []meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_UpdateDocumentsInBatches_Call {
	_c.Call.Return(taskInfos, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsInBatches_Call) RunAndReturn(run func(ctx context.Context, documentsPtr interface{}, batchSize int, opts *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_UpdateDocumentsInBatches_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocumentsNdjson provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) UpdateDocumentsNdjson(ctx context.Context, documents []byte, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documents, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocumentsNdjson")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documents, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, *meilisearch.DocumentOptions) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documents, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, *meilisearch.DocumentOptions) error); ok {
		r1 = returnFunc(ctx, documents, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_UpdateDocumentsNdjson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocumentsNdjson'
type MockmeilisearchDocumentManager_UpdateDocumentsNdjson_Call struct {
	*mock.Call
}

// UpdateDocumentsNdjson is a helper method to define mock.On call
//   - ctx context.Context
//   - documents []byte
//   - opts *meilisearch.DocumentOptions
func (_e *MockmeilisearchDocumentManager_Expecter) UpdateDocumentsNdjson(ctx any, documents any, opts any) *MockmeilisearchDocumentManager_UpdateDocumentsNdjson_Call {
	return &MockmeilisearchDocumentManager_UpdateDocumentsNdjson_Call{Call: _e.mock.On("UpdateDocumentsNdjson", ctx, documents, opts)}
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsNdjson_Call) Run(run func(ctx context.Context, documents []byte, opts *meilisearch.DocumentOptions)) *MockmeilisearchDocumentManager_UpdateDocumentsNdjson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 *meilisearch.DocumentOptions
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.DocumentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsNdjson_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_UpdateDocumentsNdjson_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsNdjson_Call) RunAndReturn(run func(ctx context.Context, documents []byte, opts *meilisearch.DocumentOptions) (*meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_UpdateDocumentsNdjson_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocumentsNdjsonInBatches provides a mock function for the type MockmeilisearchDocumentManager
func (_mock *MockmeilisearchDocumentManager) UpdateDocumentsNdjsonInBatches(ctx context.Context, documents []byte, batchsize int, opts *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, documents, batchsize, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocumentsNdjsonInBatches")
	}

	var r0 []meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int, *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, documents, batchsize, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int, *meilisearch.DocumentOptions) []meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, documents, batchsize, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, int, *meilisearch.DocumentOptions) error); ok {
		r1 = returnFunc(ctx, documents, batchsize, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchDocumentManager_UpdateDocumentsNdjsonInBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocumentsNdjsonInBatches'
type MockmeilisearchDocumentManager_UpdateDocumentsNdjsonInBatches_Call struct {
	*mock.Call
}

// UpdateDocumentsNdjsonInBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - documents []byte
//   - batchsize int
//   - opts *meilisearch.DocumentOptions
func (_e *MockmeilisearchDocumentManager_Expecter) UpdateDocumentsNdjsonInBatches(ctx any, documents any, batchsize any, opts any) *MockmeilisearchDocumentManager_UpdateDocumentsNdjsonInBatches_Call {
	return &MockmeilisearchDocumentManager_UpdateDocumentsNdjsonInBatches_Call{Call: _e.mock.On("UpdateDocumentsNdjsonInBatches", ctx, documents, batchsize, opts)}
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsNdjsonInBatches_Call) Run(run func(ctx context.Context, documents []byte, batchsize int, opts *meilisearch.DocumentOptions)) *MockmeilisearchDocumentManager_UpdateDocumentsNdjsonInBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *meilisearch.DocumentOptions
		if args[3] != nil {
			arg3 = args[3].(*meilisearch.DocumentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsNdjsonInBatches_Call) Return(taskInfos []meilisearch.TaskInfo, err error) *MockmeilisearchDocumentManager_UpdateDocumentsNdjsonInBatches_Call {
	_c.Call.Return(taskInfos, err)
	return _c
}

func (_c *MockmeilisearchDocumentManager_UpdateDocumentsNdjsonInBatches_Call) RunAndReturn(run func(ctx context.Context, documents []byte, batchsize int, opts *meilisearch.DocumentOptions) ([]meilisearch.TaskInfo, error)) *MockmeilisearchDocumentManager_UpdateDocumentsNdjsonInBatches_Call {
	_c.Call.Return(run)
	return _c
}
