// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meilisearch/meilisearch-go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockmeilisearchSettingsReader creates a new instance of MockmeilisearchSettingsReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockmeilisearchSettingsReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockmeilisearchSettingsReader {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockmeilisearchSettingsReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockmeilisearchSettingsReader is an autogenerated mock type for the SettingsReader type
type MockmeilisearchSettingsReader struct {
	mock.Mock
}

type MockmeilisearchSettingsReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockmeilisearchSettingsReader) EXPECT() *MockmeilisearchSettingsReader_Expecter {
	return &MockmeilisearchSettingsReader_Expecter{mock: &_m.Mock}
}

// GetDictionary provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetDictionary(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDictionary")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetDictionary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDictionary'
type MockmeilisearchSettingsReader_GetDictionary_Call struct {
	*mock.Call
}

// GetDictionary is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetDictionary(ctx any) *MockmeilisearchSettingsReader_GetDictionary_Call {
	return &MockmeilisearchSettingsReader_GetDictionary_Call{Call: _e.mock.On("GetDictionary", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetDictionary_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetDictionary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetDictionary_Call) Return(strings []string, err error) *MockmeilisearchSettingsReader_GetDictionary_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetDictionary_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockmeilisearchSettingsReader_GetDictionary_Call {
	_c.Call.Return(run)
	return _c
}

// GetDisplayedAttributes provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetDisplayedAttributes(ctx context.Context) (*[]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDisplayedAttributes")
	}

	var r0 *[]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*[]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *[]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetDisplayedAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDisplayedAttributes'
type MockmeilisearchSettingsReader_GetDisplayedAttributes_Call struct {
	*mock.Call
}

// GetDisplayedAttributes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetDisplayedAttributes(ctx any) *MockmeilisearchSettingsReader_GetDisplayedAttributes_Call {
	return &MockmeilisearchSettingsReader_GetDisplayedAttributes_Call{Call: _e.mock.On("GetDisplayedAttributes", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetDisplayedAttributes_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetDisplayedAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetDisplayedAttributes_Call) Return(strings *[]string, err error) *MockmeilisearchSettingsReader_GetDisplayedAttributes_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetDisplayedAttributes_Call) RunAndReturn(run func(ctx context.Context) (*[]string, error)) *MockmeilisearchSettingsReader_GetDisplayedAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// GetDistinctAttribute provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetDistinctAttribute(ctx context.Context) (*string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDistinctAttribute")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetDistinctAttribute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDistinctAttribute'
type MockmeilisearchSettingsReader_GetDistinctAttribute_Call struct {
	*mock.Call
}

// GetDistinctAttribute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetDistinctAttribute(ctx any) *MockmeilisearchSettingsReader_GetDistinctAttribute_Call {
	return &MockmeilisearchSettingsReader_GetDistinctAttribute_Call{Call: _e.mock.On("GetDistinctAttribute", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetDistinctAttribute_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetDistinctAttribute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetDistinctAttribute_Call) Return(s *string, err error) *MockmeilisearchSettingsReader_GetDistinctAttribute_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetDistinctAttribute_Call) RunAndReturn(run func(ctx context.Context) (*string, error)) *MockmeilisearchSettingsReader_GetDistinctAttribute_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmbedders provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetEmbedders(ctx context.Context) (map[string]meilisearch.Embedder, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetEmbedders")
	}

	var r0 map[string]meilisearch.Embedder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]meilisearch.Embedder, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]meilisearch.Embedder); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]meilisearch.Embedder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetEmbedders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmbedders'
type MockmeilisearchSettingsReader_GetEmbedders_Call struct {
	*mock.Call
}

// GetEmbedders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetEmbedders(ctx any) *MockmeilisearchSettingsReader_GetEmbedders_Call {
	return &MockmeilisearchSettingsReader_GetEmbedders_Call{Call: _e.mock.On("GetEmbedders", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetEmbedders_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetEmbedders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetEmbedders_Call) Return(stringToEmbedder map[string]meilisearch.Embedder, err error) *MockmeilisearchSettingsReader_GetEmbedders_Call {
	_c.Call.Return(stringToEmbedder, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetEmbedders_Call) RunAndReturn(run func(ctx context.Context) (map[string]meilisearch.Embedder, error)) *MockmeilisearchSettingsReader_GetEmbedders_Call {
	_c.Call.Return(run)
	return _c
}

// GetFacetSearch provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetFacetSearch(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFacetSearch")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetFacetSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFacetSearch'
type MockmeilisearchSettingsReader_GetFacetSearch_Call struct {
	*mock.Call
}

// GetFacetSearch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetFacetSearch(ctx any) *MockmeilisearchSettingsReader_GetFacetSearch_Call {
	return &MockmeilisearchSettingsReader_GetFacetSearch_Call{Call: _e.mock.On("GetFacetSearch", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetFacetSearch_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetFacetSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetFacetSearch_Call) Return(b bool, err error) *MockmeilisearchSettingsReader_GetFacetSearch_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetFacetSearch_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *MockmeilisearchSettingsReader_GetFacetSearch_Call {
	_c.Call.Return(run)
	return _c
}

// GetFaceting provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetFaceting(ctx context.Context) (*meilisearch.Faceting, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFaceting")
	}

	var r0 *meilisearch.Faceting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*meilisearch.Faceting, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *meilisearch.Faceting); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.Faceting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetFaceting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFaceting'
type MockmeilisearchSettingsReader_GetFaceting_Call struct {
	*mock.Call
}

// GetFaceting is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetFaceting(ctx any) *MockmeilisearchSettingsReader_GetFaceting_Call {
	return &MockmeilisearchSettingsReader_GetFaceting_Call{Call: _e.mock.On("GetFaceting", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetFaceting_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetFaceting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetFaceting_Call) Return(faceting *meilisearch.Faceting, err error) *MockmeilisearchSettingsReader_GetFaceting_Call {
	_c.Call.Return(faceting, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetFaceting_Call) RunAndReturn(run func(ctx context.Context) (*meilisearch.Faceting, error)) *MockmeilisearchSettingsReader_GetFaceting_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilterableAttributes provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetFilterableAttributes(ctx context.Context) (*[]interface{}, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFilterableAttributes")
	}

	var r0 *[]interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*[]interface{}, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *[]interface{}); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetFilterableAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilterableAttributes'
type MockmeilisearchSettingsReader_GetFilterableAttributes_Call struct {
	*mock.Call
}

// GetFilterableAttributes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetFilterableAttributes(ctx any) *MockmeilisearchSettingsReader_GetFilterableAttributes_Call {
	return &MockmeilisearchSettingsReader_GetFilterableAttributes_Call{Call: _e.mock.On("GetFilterableAttributes", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetFilterableAttributes_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetFilterableAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetFilterableAttributes_Call) Return(ifaceVals *[]interface{}, err error) *MockmeilisearchSettingsReader_GetFilterableAttributes_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetFilterableAttributes_Call) RunAndReturn(run func(ctx context.Context) (*[]interface{}, error)) *MockmeilisearchSettingsReader_GetFilterableAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// GetForeignKeys provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetForeignKeys(ctx context.Context) ([]meilisearch.ForeignKey, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetForeignKeys")
	}

	var r0 []meilisearch.ForeignKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]meilisearch.ForeignKey, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []meilisearch.ForeignKey); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]meilisearch.ForeignKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetForeignKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForeignKeys'
type MockmeilisearchSettingsReader_GetForeignKeys_Call struct {
	*mock.Call
}

// GetForeignKeys is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetForeignKeys(ctx any) *MockmeilisearchSettingsReader_GetForeignKeys_Call {
	return &MockmeilisearchSettingsReader_GetForeignKeys_Call{Call: _e.mock.On("GetForeignKeys", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetForeignKeys_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetForeignKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetForeignKeys_Call) Return(foreignKeys []meilisearch.ForeignKey, err error) *MockmeilisearchSettingsReader_GetForeignKeys_Call {
	_c.Call.Return(foreignKeys, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetForeignKeys_Call) RunAndReturn(run func(ctx context.Context) ([]meilisearch.ForeignKey, error)) *MockmeilisearchSettingsReader_GetForeignKeys_Call {
	_c.Call.Return(run)
	return _c
}

// GetLocalizedAttributes provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetLocalizedAttributes(ctx context.Context) ([]*meilisearch.LocalizedAttributes, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLocalizedAttributes")
	}

	var r0 []*meilisearch.LocalizedAttributes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*meilisearch.LocalizedAttributes, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*meilisearch.LocalizedAttributes); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*meilisearch.LocalizedAttributes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetLocalizedAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocalizedAttributes'
type MockmeilisearchSettingsReader_GetLocalizedAttributes_Call struct {
	*mock.Call
}

// GetLocalizedAttributes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetLocalizedAttributes(ctx any) *MockmeilisearchSettingsReader_GetLocalizedAttributes_Call {
	return &MockmeilisearchSettingsReader_GetLocalizedAttributes_Call{Call: _e.mock.On("GetLocalizedAttributes", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetLocalizedAttributes_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetLocalizedAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetLocalizedAttributes_Call) Return(localizedAttributess []*meilisearch.LocalizedAttributes, err error) *MockmeilisearchSettingsReader_GetLocalizedAttributes_Call {
	_c.Call.Return(localizedAttributess, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetLocalizedAttributes_Call) RunAndReturn(run func(ctx context.Context) ([]*meilisearch.LocalizedAttributes, error)) *MockmeilisearchSettingsReader_GetLocalizedAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// GetNonSeparatorTokens provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetNonSeparatorTokens(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetNonSeparatorTokens")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetNonSeparatorTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNonSeparatorTokens'
type MockmeilisearchSettingsReader_GetNonSeparatorTokens_Call struct {
	*mock.Call
}

// GetNonSeparatorTokens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetNonSeparatorTokens(ctx any) *MockmeilisearchSettingsReader_GetNonSeparatorTokens_Call {
	return &MockmeilisearchSettingsReader_GetNonSeparatorTokens_Call{Call: _e.mock.On("GetNonSeparatorTokens", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetNonSeparatorTokens_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetNonSeparatorTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetNonSeparatorTokens_Call) Return(strings []string, err error) *MockmeilisearchSettingsReader_GetNonSeparatorTokens_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetNonSeparatorTokens_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockmeilisearchSettingsReader_GetNonSeparatorTokens_Call {
	_c.Call.Return(run)
	return _c
}

// GetPagination provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetPagination(ctx context.Context) (*meilisearch.Pagination, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPagination")
	}

	var r0 *meilisearch.Pagination
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*meilisearch.Pagination, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *meilisearch.Pagination); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.Pagination)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPagination'
type MockmeilisearchSettingsReader_GetPagination_Call struct {
	*mock.Call
}

// GetPagination is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetPagination(ctx any) *MockmeilisearchSettingsReader_GetPagination_Call {
	return &MockmeilisearchSettingsReader_GetPagination_Call{Call: _e.mock.On("GetPagination", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetPagination_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetPagination_Call) Return(pagination *meilisearch.Pagination, err error) *MockmeilisearchSettingsReader_GetPagination_Call {
	_c.Call.Return(pagination, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetPagination_Call) RunAndReturn(run func(ctx context.Context) (*meilisearch.Pagination, error)) *MockmeilisearchSettingsReader_GetPagination_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrefixSearch provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetPrefixSearch(ctx context.Context) (*string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPrefixSearch")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetPrefixSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrefixSearch'
type MockmeilisearchSettingsReader_GetPrefixSearch_Call struct {
	*mock.Call
}

// GetPrefixSearch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetPrefixSearch(ctx any) *MockmeilisearchSettingsReader_GetPrefixSearch_Call {
	return &MockmeilisearchSettingsReader_GetPrefixSearch_Call{Call: _e.mock.On("GetPrefixSearch", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetPrefixSearch_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetPrefixSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetPrefixSearch_Call) Return(s *string, err error) *MockmeilisearchSettingsReader_GetPrefixSearch_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetPrefixSearch_Call) RunAndReturn(run func(ctx context.Context) (*string, error)) *MockmeilisearchSettingsReader_GetPrefixSearch_Call {
	_c.Call.Return(run)
	return _c
}

// GetProximityPrecision provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetProximityPrecision(ctx context.Context) (meilisearch.ProximityPrecisionType, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProximityPrecision")
	}

	var r0 meilisearch.ProximityPrecisionType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (meilisearch.ProximityPrecisionType, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) meilisearch.ProximityPrecisionType); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(meilisearch.ProximityPrecisionType)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetProximityPrecision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProximityPrecision'
type MockmeilisearchSettingsReader_GetProximityPrecision_Call struct {
	*mock.Call
}

// GetProximityPrecision is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetProximityPrecision(ctx any) *MockmeilisearchSettingsReader_GetProximityPrecision_Call {
	return &MockmeilisearchSettingsReader_GetProximityPrecision_Call{Call: _e.mock.On("GetProximityPrecision", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetProximityPrecision_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetProximityPrecision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetProximityPrecision_Call) Return(proximityPrecisionType meilisearch.ProximityPrecisionType, err error) *MockmeilisearchSettingsReader_GetProximityPrecision_Call {
	_c.Call.Return(proximityPrecisionType, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetProximityPrecision_Call) RunAndReturn(run func(ctx context.Context) (meilisearch.ProximityPrecisionType, error)) *MockmeilisearchSettingsReader_GetProximityPrecision_Call {
	_c.Call.Return(run)
	return _c
}

// GetRankingRules provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetRankingRules(ctx context.Context) (*[]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRankingRules")
	}

	var r0 *[]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*[]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *[]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetRankingRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRankingRules'
type MockmeilisearchSettingsReader_GetRankingRules_Call struct {
	*mock.Call
}

// GetRankingRules is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetRankingRules(ctx any) *MockmeilisearchSettingsReader_GetRankingRules_Call {
	return &MockmeilisearchSettingsReader_GetRankingRules_Call{Call: _e.mock.On("GetRankingRules", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetRankingRules_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetRankingRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetRankingRules_Call) Return(strings *[]string, err error) *MockmeilisearchSettingsReader_GetRankingRules_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetRankingRules_Call) RunAndReturn(run func(ctx context.Context) (*[]string, error)) *MockmeilisearchSettingsReader_GetRankingRules_Call {
	_c.Call.Return(run)
	return _c
}

// GetSearchCutoffMs provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetSearchCutoffMs(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSearchCutoffMs")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetSearchCutoffMs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSearchCutoffMs'
type MockmeilisearchSettingsReader_GetSearchCutoffMs_Call struct {
	*mock.Call
}

// GetSearchCutoffMs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetSearchCutoffMs(ctx any) *MockmeilisearchSettingsReader_GetSearchCutoffMs_Call {
	return &MockmeilisearchSettingsReader_GetSearchCutoffMs_Call{Call: _e.mock.On("GetSearchCutoffMs", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetSearchCutoffMs_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetSearchCutoffMs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetSearchCutoffMs_Call) Return(n int64, err error) *MockmeilisearchSettingsReader_GetSearchCutoffMs_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetSearchCutoffMs_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockmeilisearchSettingsReader_GetSearchCutoffMs_Call {
	_c.Call.Return(run)
	return _c
}

// GetSearchableAttributes provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetSearchableAttributes(ctx context.Context) (*[]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSearchableAttributes")
	}

	var r0 *[]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*[]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *[]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetSearchableAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSearchableAttributes'
type MockmeilisearchSettingsReader_GetSearchableAttributes_Call struct {
	*mock.Call
}

// GetSearchableAttributes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetSearchableAttributes(ctx any) *MockmeilisearchSettingsReader_GetSearchableAttributes_Call {
	return &MockmeilisearchSettingsReader_GetSearchableAttributes_Call{Call: _e.mock.On("GetSearchableAttributes", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetSearchableAttributes_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetSearchableAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetSearchableAttributes_Call) Return(strings *[]string, err error) *MockmeilisearchSettingsReader_GetSearchableAttributes_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetSearchableAttributes_Call) RunAndReturn(run func(ctx context.Context) (*[]string, error)) *MockmeilisearchSettingsReader_GetSearchableAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeparatorTokens provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetSeparatorTokens(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSeparatorTokens")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetSeparatorTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeparatorTokens'
type MockmeilisearchSettingsReader_GetSeparatorTokens_Call struct {
	*mock.Call
}

// GetSeparatorTokens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetSeparatorTokens(ctx any) *MockmeilisearchSettingsReader_GetSeparatorTokens_Call {
	return &MockmeilisearchSettingsReader_GetSeparatorTokens_Call{Call: _e.mock.On("GetSeparatorTokens", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetSeparatorTokens_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetSeparatorTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetSeparatorTokens_Call) Return(strings []string, err error) *MockmeilisearchSettingsReader_GetSeparatorTokens_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetSeparatorTokens_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockmeilisearchSettingsReader_GetSeparatorTokens_Call {
	_c.Call.Return(run)
	return _c
}

// GetSettings provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetSettings(ctx context.Context) (*meilisearch.Settings, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSettings")
	}

	var r0 *meilisearch.Settings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*meilisearch.Settings, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *meilisearch.Settings); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.Settings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSettings'
type MockmeilisearchSettingsReader_GetSettings_Call struct {
	*mock.Call
}

// GetSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetSettings(ctx any) *MockmeilisearchSettingsReader_GetSettings_Call {
	return &MockmeilisearchSettingsReader_GetSettings_Call{Call: _e.mock.On("GetSettings", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetSettings_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetSettings_Call) Return(settings *meilisearch.Settings, err error) *MockmeilisearchSettingsReader_GetSettings_Call {
	_c.Call.Return(settings, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetSettings_Call) RunAndReturn(run func(ctx context.Context) (*meilisearch.Settings, error)) *MockmeilisearchSettingsReader_GetSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetSortableAttributes provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetSortableAttributes(ctx context.Context) (*[]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSortableAttributes")
	}

	var r0 *[]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*[]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *[]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetSortableAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSortableAttributes'
type MockmeilisearchSettingsReader_GetSortableAttributes_Call struct {
	*mock.Call
}

// GetSortableAttributes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetSortableAttributes(ctx any) *MockmeilisearchSettingsReader_GetSortableAttributes_Call {
	return &MockmeilisearchSettingsReader_GetSortableAttributes_Call{Call: _e.mock.On("GetSortableAttributes", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetSortableAttributes_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetSortableAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetSortableAttributes_Call) Return(strings *[]string, err error) *MockmeilisearchSettingsReader_GetSortableAttributes_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetSortableAttributes_Call) RunAndReturn(run func(ctx context.Context) (*[]string, error)) *MockmeilisearchSettingsReader_GetSortableAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// GetStopWords provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetStopWords(ctx context.Context) (*[]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStopWords")
	}

	var r0 *[]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*[]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *[]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetStopWords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStopWords'
type MockmeilisearchSettingsReader_GetStopWords_Call struct {
	*mock.Call
}

// GetStopWords is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetStopWords(ctx any) *MockmeilisearchSettingsReader_GetStopWords_Call {
	return &MockmeilisearchSettingsReader_GetStopWords_Call{Call: _e.mock.On("GetStopWords", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetStopWords_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetStopWords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetStopWords_Call) Return(strings *[]string, err error) *MockmeilisearchSettingsReader_GetStopWords_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetStopWords_Call) RunAndReturn(run func(ctx context.Context) (*[]string, error)) *MockmeilisearchSettingsReader_GetStopWords_Call {
	_c.Call.Return(run)
	return _c
}

// GetSynonyms provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetSynonyms(ctx context.Context) (*map[string][]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSynonyms")
	}

	var r0 *map[string][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*map[string][]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *map[string][]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*map[string][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetSynonyms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSynonyms'
type MockmeilisearchSettingsReader_GetSynonyms_Call struct {
	*mock.Call
}

// GetSynonyms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetSynonyms(ctx any) *MockmeilisearchSettingsReader_GetSynonyms_Call {
	return &MockmeilisearchSettingsReader_GetSynonyms_Call{Call: _e.mock.On("GetSynonyms", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetSynonyms_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetSynonyms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetSynonyms_Call) Return(stringToStrings *map[string][]string, err error) *MockmeilisearchSettingsReader_GetSynonyms_Call {
	_c.Call.Return(stringToStrings, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetSynonyms_Call) RunAndReturn(run func(ctx context.Context) (*map[string][]string, error)) *MockmeilisearchSettingsReader_GetSynonyms_Call {
	_c.Call.Return(run)
	return _c
}

// GetTypoTolerance provides a mock function for the type MockmeilisearchSettingsReader
func (_mock *MockmeilisearchSettingsReader) GetTypoTolerance(ctx context.Context) (*meilisearch.TypoTolerance, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTypoTolerance")
	}

	var r0 *meilisearch.TypoTolerance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*meilisearch.TypoTolerance, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *meilisearch.TypoTolerance); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TypoTolerance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSettingsReader_GetTypoTolerance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTypoTolerance'
type MockmeilisearchSettingsReader_GetTypoTolerance_Call struct {
	*mock.Call
}

// GetTypoTolerance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSettingsReader_Expecter) GetTypoTolerance(ctx any) *MockmeilisearchSettingsReader_GetTypoTolerance_Call {
	return &MockmeilisearchSettingsReader_GetTypoTolerance_Call{Call: _e.mock.On("GetTypoTolerance", ctx)}
}

func (_c *MockmeilisearchSettingsReader_GetTypoTolerance_Call) Run(run func(ctx context.Context)) *MockmeilisearchSettingsReader_GetTypoTolerance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetTypoTolerance_Call) Return(typoTolerance *meilisearch.TypoTolerance, err error) *MockmeilisearchSettingsReader_GetTypoTolerance_Call {
	_c.Call.Return(typoTolerance, err)
	return _c
}

func (_c *MockmeilisearchSettingsReader_GetTypoTolerance_Call) RunAndReturn(run func(ctx context.Context) (*meilisearch.TypoTolerance, error)) *MockmeilisearchSettingsReader_GetTypoTolerance_Call {
	_c.Call.Return(run)
	return _c
}
