// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meilisearch/meilisearch-go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockmeilisearchIndexReader creates a new instance of MockmeilisearchIndexReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockmeilisearchIndexReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockmeilisearchIndexReader {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockmeilisearchIndexReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockmeilisearchIndexReader is an autogenerated mock type for the IndexReader type
type MockmeilisearchIndexReader struct {
	mock.Mock
}

type MockmeilisearchIndexReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockmeilisearchIndexReader) EXPECT() *MockmeilisearchIndexReader_Expecter {
	return &MockmeilisearchIndexReader_Expecter{mock: &_m.Mock}
}

// FetchInfo provides a mock function for the type MockmeilisearchIndexReader
func (_mock *MockmeilisearchIndexReader) FetchInfo(ctx context.Context) (*meilisearch.IndexResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchInfo")
	}

	var r0 *meilisearch.IndexResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*meilisearch.IndexResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *meilisearch.IndexResult); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.IndexResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchIndexReader_FetchInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchInfo'
type MockmeilisearchIndexReader_FetchInfo_Call struct {
	*mock.Call
}

// FetchInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchIndexReader_Expecter) FetchInfo(ctx any) *MockmeilisearchIndexReader_FetchInfo_Call {
	return &MockmeilisearchIndexReader_FetchInfo_Call{Call: _e.mock.On("FetchInfo", ctx)}
}

func (_c *MockmeilisearchIndexReader_FetchInfo_Call) Run(run func(ctx context.Context)) *MockmeilisearchIndexReader_FetchInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchIndexReader_FetchInfo_Call) Return(indexResult *meilisearch.IndexResult, err error) *MockmeilisearchIndexReader_FetchInfo_Call {
	_c.Call.Return(indexResult, err)
	return _c
}

func (_c *MockmeilisearchIndexReader_FetchInfo_Call) RunAndReturn(run func(ctx context.Context) (*meilisearch.IndexResult, error)) *MockmeilisearchIndexReader_FetchInfo_Call {
	_c.Call.Return(run)
	return _c
}

// FetchPrimaryKey provides a mock function for the type MockmeilisearchIndexReader
func (_mock *MockmeilisearchIndexReader) FetchPrimaryKey(ctx context.Context) (*string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchPrimaryKey")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchIndexReader_FetchPrimaryKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPrimaryKey'
type MockmeilisearchIndexReader_FetchPrimaryKey_Call struct {
	*mock.Call
}

// FetchPrimaryKey is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchIndexReader_Expecter) FetchPrimaryKey(ctx any) *MockmeilisearchIndexReader_FetchPrimaryKey_Call {
	return &MockmeilisearchIndexReader_FetchPrimaryKey_Call{Call: _e.mock.On("FetchPrimaryKey", ctx)}
}

func (_c *MockmeilisearchIndexReader_FetchPrimaryKey_Call) Run(run func(ctx context.Context)) *MockmeilisearchIndexReader_FetchPrimaryKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchIndexReader_FetchPrimaryKey_Call) Return(s *string, err error) *MockmeilisearchIndexReader_FetchPrimaryKey_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockmeilisearchIndexReader_FetchPrimaryKey_Call) RunAndReturn(run func(ctx context.Context) (*string, error)) *MockmeilisearchIndexReader_FetchPrimaryKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function for the type MockmeilisearchIndexReader
func (_mock *MockmeilisearchIndexReader) GetStats(ctx context.Context, param *meilisearch.StatsParams) (*meilisearch.StatsIndex, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *meilisearch.StatsIndex
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *meilisearch.StatsParams) (*meilisearch.StatsIndex, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *meilisearch.StatsParams) *meilisearch.StatsIndex); ok {
		r0 = returnFunc(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.StatsIndex)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *meilisearch.StatsParams) error); ok {
		r1 = returnFunc(ctx, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchIndexReader_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockmeilisearchIndexReader_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - param *meilisearch.StatsParams
func (_e *MockmeilisearchIndexReader_Expecter) GetStats(ctx any, param any) *MockmeilisearchIndexReader_GetStats_Call {
	return &MockmeilisearchIndexReader_GetStats_Call{Call: _e.mock.On("GetStats", ctx, param)}
}

func (_c *MockmeilisearchIndexReader_GetStats_Call) Run(run func(ctx context.Context, param *meilisearch.StatsParams)) *MockmeilisearchIndexReader_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *meilisearch.StatsParams
		if args[1] != nil {
			arg1 = args[1].(*meilisearch.StatsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockmeilisearchIndexReader_GetStats_Call) Return(statsIndex *meilisearch.StatsIndex, err error) *MockmeilisearchIndexReader_GetStats_Call {
	_c.Call.Return(statsIndex, err)
	return _c
}

func (_c *MockmeilisearchIndexReader_GetStats_Call) RunAndReturn(run func(ctx context.Context, param *meilisearch.StatsParams) (*meilisearch.StatsIndex, error)) *MockmeilisearchIndexReader_GetStats_Call {
	_c.Call.Return(run)
	return _c
}
