// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meilisearch/meilisearch-go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockmeilisearchSearchRulesManager creates a new instance of MockmeilisearchSearchRulesManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockmeilisearchSearchRulesManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockmeilisearchSearchRulesManager {
	mock := &MockmeilisearchSearchRulesManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockmeilisearchSearchRulesManager is an autogenerated mock type for the SearchRulesManager type
type MockmeilisearchSearchRulesManager struct {
	mock.Mock
}

type MockmeilisearchSearchRulesManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockmeilisearchSearchRulesManager) EXPECT() *MockmeilisearchSearchRulesManager_Expecter {
	return &MockmeilisearchSearchRulesManager_Expecter{mock: &_m.Mock}
}

// DeleteAllSearchRules provides a mock function for the type MockmeilisearchSearchRulesManager
func (_mock *MockmeilisearchSearchRulesManager) DeleteAllSearchRules() (*meilisearch.TaskInfo, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllSearchRules")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*meilisearch.TaskInfo, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *meilisearch.TaskInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSearchRulesManager_DeleteAllSearchRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllSearchRules'
type MockmeilisearchSearchRulesManager_DeleteAllSearchRules_Call struct {
	*mock.Call
}

// DeleteAllSearchRules is a helper method to define mock.On call
func (_e *MockmeilisearchSearchRulesManager_Expecter) DeleteAllSearchRules() *MockmeilisearchSearchRulesManager_DeleteAllSearchRules_Call {
	return &MockmeilisearchSearchRulesManager_DeleteAllSearchRules_Call{Call: _e.mock.On("DeleteAllSearchRules")}
}

func (_c *MockmeilisearchSearchRulesManager_DeleteAllSearchRules_Call) Run(run func()) *MockmeilisearchSearchRulesManager_DeleteAllSearchRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_DeleteAllSearchRules_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchSearchRulesManager_DeleteAllSearchRules_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_DeleteAllSearchRules_Call) RunAndReturn(run func() (*meilisearch.TaskInfo, error)) *MockmeilisearchSearchRulesManager_DeleteAllSearchRules_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllSearchRulesWithContext provides a mock function for the type MockmeilisearchSearchRulesManager
func (_mock *MockmeilisearchSearchRulesManager) DeleteAllSearchRulesWithContext(ctx context.Context) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllSearchRulesWithContext")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSearchRulesManager_DeleteAllSearchRulesWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllSearchRulesWithContext'
type MockmeilisearchSearchRulesManager_DeleteAllSearchRulesWithContext_Call struct {
	*mock.Call
}

// DeleteAllSearchRulesWithContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockmeilisearchSearchRulesManager_Expecter) DeleteAllSearchRulesWithContext(ctx interface{}) *MockmeilisearchSearchRulesManager_DeleteAllSearchRulesWithContext_Call {
	return &MockmeilisearchSearchRulesManager_DeleteAllSearchRulesWithContext_Call{Call: _e.mock.On("DeleteAllSearchRulesWithContext", ctx)}
}

func (_c *MockmeilisearchSearchRulesManager_DeleteAllSearchRulesWithContext_Call) Run(run func(ctx context.Context)) *MockmeilisearchSearchRulesManager_DeleteAllSearchRulesWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_DeleteAllSearchRulesWithContext_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchSearchRulesManager_DeleteAllSearchRulesWithContext_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_DeleteAllSearchRulesWithContext_Call) RunAndReturn(run func(ctx context.Context) (*meilisearch.TaskInfo, error)) *MockmeilisearchSearchRulesManager_DeleteAllSearchRulesWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSearchRule provides a mock function for the type MockmeilisearchSearchRulesManager
func (_mock *MockmeilisearchSearchRulesManager) DeleteSearchRule(uid string) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSearchRule")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(uid)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSearchRulesManager_DeleteSearchRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSearchRule'
type MockmeilisearchSearchRulesManager_DeleteSearchRule_Call struct {
	*mock.Call
}

// DeleteSearchRule is a helper method to define mock.On call
//   - uid string
func (_e *MockmeilisearchSearchRulesManager_Expecter) DeleteSearchRule(uid interface{}) *MockmeilisearchSearchRulesManager_DeleteSearchRule_Call {
	return &MockmeilisearchSearchRulesManager_DeleteSearchRule_Call{Call: _e.mock.On("DeleteSearchRule", uid)}
}

func (_c *MockmeilisearchSearchRulesManager_DeleteSearchRule_Call) Run(run func(uid string)) *MockmeilisearchSearchRulesManager_DeleteSearchRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_DeleteSearchRule_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchSearchRulesManager_DeleteSearchRule_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_DeleteSearchRule_Call) RunAndReturn(run func(uid string) (*meilisearch.TaskInfo, error)) *MockmeilisearchSearchRulesManager_DeleteSearchRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSearchRuleWithContext provides a mock function for the type MockmeilisearchSearchRulesManager
func (_mock *MockmeilisearchSearchRulesManager) DeleteSearchRuleWithContext(ctx context.Context, uid string) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSearchRuleWithContext")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSearchRulesManager_DeleteSearchRuleWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSearchRuleWithContext'
type MockmeilisearchSearchRulesManager_DeleteSearchRuleWithContext_Call struct {
	*mock.Call
}

// DeleteSearchRuleWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockmeilisearchSearchRulesManager_Expecter) DeleteSearchRuleWithContext(ctx interface{}, uid interface{}) *MockmeilisearchSearchRulesManager_DeleteSearchRuleWithContext_Call {
	return &MockmeilisearchSearchRulesManager_DeleteSearchRuleWithContext_Call{Call: _e.mock.On("DeleteSearchRuleWithContext", ctx, uid)}
}

func (_c *MockmeilisearchSearchRulesManager_DeleteSearchRuleWithContext_Call) Run(run func(ctx context.Context, uid string)) *MockmeilisearchSearchRulesManager_DeleteSearchRuleWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_DeleteSearchRuleWithContext_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchSearchRulesManager_DeleteSearchRuleWithContext_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_DeleteSearchRuleWithContext_Call) RunAndReturn(run func(ctx context.Context, uid string) (*meilisearch.TaskInfo, error)) *MockmeilisearchSearchRulesManager_DeleteSearchRuleWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetSearchRule provides a mock function for the type MockmeilisearchSearchRulesManager
func (_mock *MockmeilisearchSearchRulesManager) GetSearchRule(uid string) (*meilisearch.SearchRule, error) {
	ret := _mock.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for GetSearchRule")
	}

	var r0 *meilisearch.SearchRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*meilisearch.SearchRule, error)); ok {
		return returnFunc(uid)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *meilisearch.SearchRule); ok {
		r0 = returnFunc(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.SearchRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSearchRulesManager_GetSearchRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSearchRule'
type MockmeilisearchSearchRulesManager_GetSearchRule_Call struct {
	*mock.Call
}

// GetSearchRule is a helper method to define mock.On call
//   - uid string
func (_e *MockmeilisearchSearchRulesManager_Expecter) GetSearchRule(uid interface{}) *MockmeilisearchSearchRulesManager_GetSearchRule_Call {
	return &MockmeilisearchSearchRulesManager_GetSearchRule_Call{Call: _e.mock.On("GetSearchRule", uid)}
}

func (_c *MockmeilisearchSearchRulesManager_GetSearchRule_Call) Run(run func(uid string)) *MockmeilisearchSearchRulesManager_GetSearchRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_GetSearchRule_Call) Return(searchRule *meilisearch.SearchRule, err error) *MockmeilisearchSearchRulesManager_GetSearchRule_Call {
	_c.Call.Return(searchRule, err)
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_GetSearchRule_Call) RunAndReturn(run func(uid string) (*meilisearch.SearchRule, error)) *MockmeilisearchSearchRulesManager_GetSearchRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetSearchRuleWithContext provides a mock function for the type MockmeilisearchSearchRulesManager
func (_mock *MockmeilisearchSearchRulesManager) GetSearchRuleWithContext(ctx context.Context, uid string) (*meilisearch.SearchRule, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetSearchRuleWithContext")
	}

	var r0 *meilisearch.SearchRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*meilisearch.SearchRule, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *meilisearch.SearchRule); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.SearchRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSearchRulesManager_GetSearchRuleWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSearchRuleWithContext'
type MockmeilisearchSearchRulesManager_GetSearchRuleWithContext_Call struct {
	*mock.Call
}

// GetSearchRuleWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockmeilisearchSearchRulesManager_Expecter) GetSearchRuleWithContext(ctx interface{}, uid interface{}) *MockmeilisearchSearchRulesManager_GetSearchRuleWithContext_Call {
	return &MockmeilisearchSearchRulesManager_GetSearchRuleWithContext_Call{Call: _e.mock.On("GetSearchRuleWithContext", ctx, uid)}
}

func (_c *MockmeilisearchSearchRulesManager_GetSearchRuleWithContext_Call) Run(run func(ctx context.Context, uid string)) *MockmeilisearchSearchRulesManager_GetSearchRuleWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_GetSearchRuleWithContext_Call) Return(searchRule *meilisearch.SearchRule, err error) *MockmeilisearchSearchRulesManager_GetSearchRuleWithContext_Call {
	_c.Call.Return(searchRule, err)
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_GetSearchRuleWithContext_Call) RunAndReturn(run func(ctx context.Context, uid string) (*meilisearch.SearchRule, error)) *MockmeilisearchSearchRulesManager_GetSearchRuleWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ListSearchRules provides a mock function for the type MockmeilisearchSearchRulesManager
func (_mock *MockmeilisearchSearchRulesManager) ListSearchRules(params *meilisearch.SearchRulesParams) (*meilisearch.SearchRulesResults, error) {
	ret := _mock.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for ListSearchRules")
	}

	var r0 *meilisearch.SearchRulesResults
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*meilisearch.SearchRulesParams) (*meilisearch.SearchRulesResults, error)); ok {
		return returnFunc(params)
	}
	if returnFunc, ok := ret.Get(0).(func(*meilisearch.SearchRulesParams) *meilisearch.SearchRulesResults); ok {
		r0 = returnFunc(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.SearchRulesResults)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*meilisearch.SearchRulesParams) error); ok {
		r1 = returnFunc(params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSearchRulesManager_ListSearchRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSearchRules'
type MockmeilisearchSearchRulesManager_ListSearchRules_Call struct {
	*mock.Call
}

// ListSearchRules is a helper method to define mock.On call
//   - params *meilisearch.SearchRulesParams
func (_e *MockmeilisearchSearchRulesManager_Expecter) ListSearchRules(params interface{}) *MockmeilisearchSearchRulesManager_ListSearchRules_Call {
	return &MockmeilisearchSearchRulesManager_ListSearchRules_Call{Call: _e.mock.On("ListSearchRules", params)}
}

func (_c *MockmeilisearchSearchRulesManager_ListSearchRules_Call) Run(run func(params *meilisearch.SearchRulesParams)) *MockmeilisearchSearchRulesManager_ListSearchRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *meilisearch.SearchRulesParams
		if args[0] != nil {
			arg0 = args[0].(*meilisearch.SearchRulesParams)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_ListSearchRules_Call) Return(searchRulesResults *meilisearch.SearchRulesResults, err error) *MockmeilisearchSearchRulesManager_ListSearchRules_Call {
	_c.Call.Return(searchRulesResults, err)
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_ListSearchRules_Call) RunAndReturn(run func(params *meilisearch.SearchRulesParams) (*meilisearch.SearchRulesResults, error)) *MockmeilisearchSearchRulesManager_ListSearchRules_Call {
	_c.Call.Return(run)
	return _c
}

// ListSearchRulesWithContext provides a mock function for the type MockmeilisearchSearchRulesManager
func (_mock *MockmeilisearchSearchRulesManager) ListSearchRulesWithContext(ctx context.Context, params *meilisearch.SearchRulesParams) (*meilisearch.SearchRulesResults, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListSearchRulesWithContext")
	}

	var r0 *meilisearch.SearchRulesResults
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *meilisearch.SearchRulesParams) (*meilisearch.SearchRulesResults, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *meilisearch.SearchRulesParams) *meilisearch.SearchRulesResults); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.SearchRulesResults)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *meilisearch.SearchRulesParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSearchRulesManager_ListSearchRulesWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSearchRulesWithContext'
type MockmeilisearchSearchRulesManager_ListSearchRulesWithContext_Call struct {
	*mock.Call
}

// ListSearchRulesWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - params *meilisearch.SearchRulesParams
func (_e *MockmeilisearchSearchRulesManager_Expecter) ListSearchRulesWithContext(ctx interface{}, params interface{}) *MockmeilisearchSearchRulesManager_ListSearchRulesWithContext_Call {
	return &MockmeilisearchSearchRulesManager_ListSearchRulesWithContext_Call{Call: _e.mock.On("ListSearchRulesWithContext", ctx, params)}
}

func (_c *MockmeilisearchSearchRulesManager_ListSearchRulesWithContext_Call) Run(run func(ctx context.Context, params *meilisearch.SearchRulesParams)) *MockmeilisearchSearchRulesManager_ListSearchRulesWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *meilisearch.SearchRulesParams
		if args[1] != nil {
			arg1 = args[1].(*meilisearch.SearchRulesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_ListSearchRulesWithContext_Call) Return(searchRulesResults *meilisearch.SearchRulesResults, err error) *MockmeilisearchSearchRulesManager_ListSearchRulesWithContext_Call {
	_c.Call.Return(searchRulesResults, err)
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_ListSearchRulesWithContext_Call) RunAndReturn(run func(ctx context.Context, params *meilisearch.SearchRulesParams) (*meilisearch.SearchRulesResults, error)) *MockmeilisearchSearchRulesManager_ListSearchRulesWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSearchRule provides a mock function for the type MockmeilisearchSearchRulesManager
func (_mock *MockmeilisearchSearchRulesManager) UpdateSearchRule(uid string, params *meilisearch.SearchRulesRequest) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(uid, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSearchRule")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *meilisearch.SearchRulesRequest) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(uid, params)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *meilisearch.SearchRulesRequest) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(uid, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *meilisearch.SearchRulesRequest) error); ok {
		r1 = returnFunc(uid, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSearchRulesManager_UpdateSearchRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSearchRule'
type MockmeilisearchSearchRulesManager_UpdateSearchRule_Call struct {
	*mock.Call
}

// UpdateSearchRule is a helper method to define mock.On call
//   - uid string
//   - params *meilisearch.SearchRulesRequest
func (_e *MockmeilisearchSearchRulesManager_Expecter) UpdateSearchRule(uid interface{}, params interface{}) *MockmeilisearchSearchRulesManager_UpdateSearchRule_Call {
	return &MockmeilisearchSearchRulesManager_UpdateSearchRule_Call{Call: _e.mock.On("UpdateSearchRule", uid, params)}
}

func (_c *MockmeilisearchSearchRulesManager_UpdateSearchRule_Call) Run(run func(uid string, params *meilisearch.SearchRulesRequest)) *MockmeilisearchSearchRulesManager_UpdateSearchRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *meilisearch.SearchRulesRequest
		if args[1] != nil {
			arg1 = args[1].(*meilisearch.SearchRulesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_UpdateSearchRule_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchSearchRulesManager_UpdateSearchRule_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_UpdateSearchRule_Call) RunAndReturn(run func(uid string, params *meilisearch.SearchRulesRequest) (*meilisearch.TaskInfo, error)) *MockmeilisearchSearchRulesManager_UpdateSearchRule_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSearchRuleWithContext provides a mock function for the type MockmeilisearchSearchRulesManager
func (_mock *MockmeilisearchSearchRulesManager) UpdateSearchRuleWithContext(ctx context.Context, uid string, params *meilisearch.SearchRulesRequest) (*meilisearch.TaskInfo, error) {
	ret := _mock.Called(ctx, uid, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSearchRuleWithContext")
	}

	var r0 *meilisearch.TaskInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *meilisearch.SearchRulesRequest) (*meilisearch.TaskInfo, error)); ok {
		return returnFunc(ctx, uid, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *meilisearch.SearchRulesRequest) *meilisearch.TaskInfo); ok {
		r0 = returnFunc(ctx, uid, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.TaskInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *meilisearch.SearchRulesRequest) error); ok {
		r1 = returnFunc(ctx, uid, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockmeilisearchSearchRulesManager_UpdateSearchRuleWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSearchRuleWithContext'
type MockmeilisearchSearchRulesManager_UpdateSearchRuleWithContext_Call struct {
	*mock.Call
}

// UpdateSearchRuleWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
//   - params *meilisearch.SearchRulesRequest
func (_e *MockmeilisearchSearchRulesManager_Expecter) UpdateSearchRuleWithContext(ctx interface{}, uid interface{}, params interface{}) *MockmeilisearchSearchRulesManager_UpdateSearchRuleWithContext_Call {
	return &MockmeilisearchSearchRulesManager_UpdateSearchRuleWithContext_Call{Call: _e.mock.On("UpdateSearchRuleWithContext", ctx, uid, params)}
}

func (_c *MockmeilisearchSearchRulesManager_UpdateSearchRuleWithContext_Call) Run(run func(ctx context.Context, uid string, params *meilisearch.SearchRulesRequest)) *MockmeilisearchSearchRulesManager_UpdateSearchRuleWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *meilisearch.SearchRulesRequest
		if args[2] != nil {
			arg2 = args[2].(*meilisearch.SearchRulesRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_UpdateSearchRuleWithContext_Call) Return(taskInfo *meilisearch.TaskInfo, err error) *MockmeilisearchSearchRulesManager_UpdateSearchRuleWithContext_Call {
	_c.Call.Return(taskInfo, err)
	return _c
}

func (_c *MockmeilisearchSearchRulesManager_UpdateSearchRuleWithContext_Call) RunAndReturn(run func(ctx context.Context, uid string, params *meilisearch.SearchRulesRequest) (*meilisearch.TaskInfo, error)) *MockmeilisearchSearchRulesManager_UpdateSearchRuleWithContext_Call {
	_c.Call.Return(run)
	return _c
}
